name: 🐧 Linux Build
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build Release
        run: |
          rustup default stable
          cargo build --release

      - name: Store Linux
        uses: actions/upload-artifact@v3
        with:
          name: qml_formatter-${{ runner.os }}-${{ matrix.toolchain }}
          path: target/release/qml_formatter

      - name: Automatic pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Nightly builds"
          automatic_release_tag: "latest"
          files: |
            target/release/qml_formatter
