name: 🐧 Linux Clippy
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    strategy:
      matrix:
        toolchain: [ stable ]
        type: [ release ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Clippy
        run: |
          rustup default stable
          cargo clippy
